on: workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: run PlatformIO Dependabot
        uses: peterus/platformio_dependabot@0.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo_path: 'peterus/ESP-FTP-Server-Lib'
